[package]
name = "launchpad-cli"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[[bin]]
name = "launchpad"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
common.workspace = true
clap.workspace = true
hex.workspace = true
launchpad-client.workspace = true
pool.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
wallet.workspace = true

[lints]
workspace = true
