#!/usr/bin/env bash
set -euo pipefail

# The default LEZ template has hand-written dispatch.  These declarations are
# its SPEL-facing ABI, generated by the project-pinned `spel` binary.
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$root"
mkdir -p idl

for program in curve factory private_buy; do
  temp=$(mktemp)
  lgs spel -- generate-idl "idl-src/${program}.rs" > "$temp"
  mv "$temp" "idl/${program}.json"
done
